name: Run MATLAB command
on: push
jobs:
    job1:
        name: Run MATLAB Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              
            - name: Set up MATLAB
              uses: matlab-actions/setup-matlab@v1
              
            - name: exec MATLAB 'ver' command
              uses: matlab-actions/run-command@v1
              with:
                  command: ver
            
