name: Generate Test Artifacts on GitHub-Hosted Runner
on: push
jobs:
  my-job:
    name: Run MATLAB Tests and Generate Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Run MATLAB Tests
        # You may pin to the exact commit or the version.
        # uses: matlab-actions/run-tests@45eb98a48208056c40a052f21f758da97b9b0a89
        uses: matlab-actions/run-tests@v1.0.1
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: TestResult/*.xml
